services:
  redis:
    image: "redis:latest"
    ports:
      - '6379:6379'
    container_name: redis
    tty: true
    networks:
      logcomex:
        ipv4_address: 192.168.5.5
#  webserver:
#    image: "nginx:1.17.10"
#    container_name: webserver
#    ports:
#      - '80:80'
#      - '443:443'
#    volumes:
#      - ./docker/webserver/default.conf:/etc/nginx/conf.d/default.conf
#    networks:
#      logcomex:
#        ipv4_address: 192.168.5.2
  laravel:
    build:
      context: backend
      dockerfile: ../docker/laravel/Dockerfile
    container_name: laravel
    working_dir: /srv/app/
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/srv/app/
#      - ./docker/laravel/overrides.conf:/etc/php/8.3/fpm/pool.d/z-overrides.conf
    extra_hosts:
      - host:host-gateway
    networks:
      logcomex:
        ipv4_address: 192.168.5.3
  database:
    image: "postgres:latest"
    container_name: database
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=logcomex
      - POSTGRES_USER=marcio
      - POSTGRES_PASSWORD=123456789
    networks:
      logcomex:
        ipv4_address: 192.168.5.4
  vue:
    image: node:latest
    container_name: vue_app
    working_dir: /srv/app
    command: npm run dev -- --host=0.0.0.0
    volumes:
      - ${PWD}/frontend:/srv/app/
    ports:
      - '5173:5173'
    networks:
      logcomex:
        ipv4_address: 192.168.5.6
networks:
  logcomex:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.5.0/24
